# Generated by Django 3.0.1 on 2020-01-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='mood',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
