# Generated by Django 3.0.1 on 2020-01-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200120_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
    ]
