# Generated by Django 3.0.1 on 2020-01-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
